#!/bin/bash/
apt update && apt install -y \
    apache-users \
    apache2 \
    cadaver \
    commix \
    davtest \
    default-mysql-server \
    dirb \
    dotdotpwn \
    eyewitness \
    ferret-sidejack \
    ftester \
    hakrawler \
    hamster-sidejack \
    heartleech \
    httprint \
    httrack \
    hydra \
    hydra-gtk \
    jboss-autopwn \
    joomscan \
    laudanum \
    lbd \
    medusa \
    mitmproxy \
    ncrack \
    nikto \
    nishang \
    nmap \
    oscanner \
    padbuster \
    patator \
    php \
    php-mysql \
    plecost \
    proxychains4 \
    proxytunnel \
    qsslcaudit \
    redsocks \
    sidguesser \
    siege \
    skipfish \
    slowhttptest \
    sqldict \
    sqlitebrowser \
    sqlmap \
    sqlninja \
    sqlsus \
    ssldump \
    sslh \
    sslscan \
    sslsniff \
    sslsplit \
    sslyze \
    stunnel4 \
    thc-ssl-dos \
    tlssled \
    tnscmd10g \
    uniscan \
    wafw00f \
    wapiti \
    watobo \
    webacoo \
    webshells \
    weevely \
    wfuzz \
    whatweb \
    wpscan \
    xsser
#    zaproxy
#    beef-xss
#    burpsuite
#    wireshark
#    webscarab
#    paros
#    owasp-mantra-ff
#    maltego
#    jsql-injection
#    dirbuster
#    cutycapt